apiVersion: apps/v1
kind: Deployment
metadata:
  name: configure-alertmanager-operator
  namespace: openshift-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: configure-alertmanager-operator
  template:
    metadata:
      labels:
        name: configure-alertmanager-operator
    spec:
      serviceAccountName: configure-alertmanager-operator
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
            weight: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
      containers:
        - name: configure-alertmanager-operator
          image: quay.io/redhat-services-prod/camo-hcm-tenant/configure-alertmanager-operator-master/configure-alertmanager-operator-master@sha256:2b3522780c0970439d2fd5c8c76f655a7ed390e0aeef0c353e1b182940ba1b3b
          command:
          - configure-alertmanager-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "configure-alertmanager-operator"
            - name: FEDRAMP
              value: "false"
